plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Exclude:
    - "lib/email/sender.rb"
    - "lib/email/sender/message.rb"
    - "test/email/test_sender.rb"
    - "test/email/test_message.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/email/sender/message.rb"
    - "test/email/test_message.rb"

Metrics/ParameterLists:
  Exclude:
    - "lib/email/sender.rb"
    - "lib/email/sender/message.rb"
